### ISSUE TITLE
Is adapter died?

### ISSUE THREAD

**Issue by barloc** [vertica/dbt-vertica#103]
Hello.
There are some critical bugs, and some pool requests with fixes, but nobody care about it :(
Microfocus kills opensource adapter?
May be return it to the open source?
How you think, @andyreagan @mpcarter?

**Comment by ajay-abrol2** [comment]
Hi Brrlaoc,

I am currently working on to upgrade dbt core 1.5.0 and about to finish my development then merge code accordingly.

Regards,
Ajay Abrol

**Comment by barloc** [comment]
Thank you for fast reply.

**Comment by lauripe** [comment]
When the 1.5 is going to be released / put to PyPI?

**Comment by barloc** [comment]
https://github.com/vertica/dbt-vertica/blob/master/setup.py#L81
I don't understand why it is not in pypl :(

**Comment by ajay-abrol2** [comment]
I have released latest code to PyPI.

**Comment by lauripe** [comment]
Thanks!
