### ISSUE TITLE
ErrorResponse is not imported in connections.py

### ISSUE THREAD

**Issue by perttus** [vertica/dbt-vertica#111]
I noticed that [`get_result_from_cursor`](https://github.com/vertica/dbt-vertica/blob/f84cb92b08c5d6160d178f255fa82526d2fb7584/dbt/adapters/vertica/connections.py#L199) is failing since `ErrorResponse` is not imported. There are a few other Pylance errors as well that could be easily caught with e.g. super-linter in CI pipeline.

**Comment by ajay-abrol2** [comment]
PR is merged so please verify and close this bug.

**Comment by perttus** [comment]
Thank you! 👍
