### ISSUE TITLE
Database and schema are defined in base class

### ISSUE THREAD

**Issue by andyreagan** [vertica/dbt-vertica#24]
We don't need to redefine `database` or `schema` here:

https://github.com/ahedengren/dbt-vertica/blob/703ecc7afcbdd518f69b0730dd76538a90207989/dbt/adapters/vertica/connections.py#L23

See the base class:

https://github.com/dbt-labs/dbt-core/blob/43e3fc22c4eae4d3d901faba05e33c40f1f1dc5a/core/dbt/contracts/connection.py#L124

**Comment by ahedengren** [comment]
Good catch. Easy fix :)
