### ISSUE TITLE
Bug with handling of the multistatement queries

### ISSUE THREAD

**Issue by barloc** [vertica/dbt-vertica#26]
Hello
We found bug in old version (0.19) and it is in newest versions too.
vertica-python library doesn't handle errors in second(and later) query in the multi statement query.
So if we have incremental model with pipeline: create temp result table, delete unique keys from target table, insert from temp table to result - if there are errors on step 2 or 3 - DBT decides that all is correct, but data doesn't insert to table.
More info on link: https://github.com/vertica/vertica-python#nextset
In version 0.19 I fixed it with overwriting core methods: https://github.com/chapsuk/dbt-vertica/pull/4 (ugly code, sorry :()

**Comment by ahedengren** [comment]
Hi @barloc ,

Could you push a PR upstream to us so we can see the fix itself? Would be interesting to see.

**Comment by ahedengren** [comment]
Hi @barloc,

Could you push your fork upstream to us so we can check it out? Thanks!

**Comment by barloc** [comment]
https://github.com/ahedengren/dbt-vertica/pull/27

**Comment by Sachin-Thakur** [comment]
Hi  @barloc  could you pleaee try this senario with our  repo installation https://github.com/Sachin-Thakur/dbt-vertica-3x
