### ISSUE TITLE
add adapter to dbt docs's "Available Adapters" page

### ISSUE THREAD

**Issue by dataders** [vertica/dbt-vertica#28]
The [Available Adapters](https://docs.getdbt.com/docs/available-adapters) page is one of the dbt community's most-visited docs pages. It would be of great benefit for first-time visitors to the dbt docs to see:
1. that this adapter is a possible option for using dbt-core, and
2. how many large the dbt ecosystem of support databases is.

https://github.com/dbt-labs/docs.getdbt.com/issues/1489 exists to address this with all as-of-yet undocumented adapters.

We just released [Documenting a new adapter](https://docs.getdbt.com/docs/contributing/documenting-a-new-adapter), a new guide on how to add an adapter to the Available Adapters page. I'd love to see this adapter on that page, so feel free to reach out with any questions/blockers by either replying to this issue, or posting in the #adapter-ecosystem channel of the dbt Community Slack.

Looking forward to the contribution!

**Comment by andyreagan** [comment]
@dataders I tried adding this back in Oct 2021: https://github.com/dbt-labs/docs.getdbt.com/pull/882

**Comment by dataders** [comment]
> @dataders I tried adding this back in Oct 2021: [dbt-labs/docs.getdbt.com#882](https://github.com/dbt-labs/docs.getdbt.com/pull/882)

well thanks for being on your A-game! sorry I dropped the ball on this. I'd love to help you get that PR in, but can you update from the main branch and resolve any conflicts? there's been lots of changes to our docs page since then

**Comment by ahedengren** [comment]
Hi @dataders ,

I added Vertica to the community supported list February 2022: https://github.com/dbt-labs/docs.getdbt.com/pull/1128.

We should probably update it now that it's Vendor supported by Vertica now.

**Comment by dataders** [comment]
> Hi @dataders ,
> 
> 
> 
> I added Vertica to the community supported list February 2022: https://github.com/dbt-labs/docs.getdbt.com/pull/1128.
> 
> 
> 
> We should probably update it now that it's Vendor supported by Vertica now.

Ah whoops -- my bad! I do think you're right that a PR to move it to the "vendor-supported" table is justified. Additionally a dedicated "config" page as mentioned in the new docs page would be of use to end-users!

**Comment by ahedengren** [comment]
Hi @dataders ,

No worries! I did flub adding it the first time! 😮 Thank you for the good feedback to add a dedicated "config" page there. Perhaps it's something for either the existing maintainers or the new dbt-veritca maintainers to do. 😄 Either case, we should get it done, and soon-ish!
