### ISSUE TITLE
Tests for 1.1+ version

### ISSUE THREAD

**Issue by barloc** [vertica/dbt-vertica#42]
Hello
From version 1.1 dbt-core moved to other test methods for adapters (more info [here](https://docs.getdbt.com/docs/contributing/adapter-development/4-testing-a-new-adapter)).
So what do you think to do with it?

**Comment by andyreagan** [comment]
This is a good catch. We should update them...

**Comment by andyreagan** [comment]
Looking at the state of things here - I think we need to

1. Automate existing tests using vertica-ce docker container in github action.
2. Use these tests to merge in good PR's (there are 7 open!).
3. Clean up resolved issues once good PR's merged.
4. Update the testing format.

**Comment by andyreagan** [comment]
I'll take a pass at (1) as soon as tomorrow, since I have a work project that can really use one of the open PRs (I'm eager to merge it).

**Comment by andyreagan** [comment]
I went ahead and upgraded the tests, forgoing the aforementioned steps. We can address the open PRs with the new test framework in place.
