### ISSUE TITLE
There is a bug in dbt vertica when running --full-refresh on incremental models.

### ISSUE THREAD

**Issue by uzahid** [vertica/dbt-vertica#74]
When it is run the first time and the table already exists, full refresh on incremental models fails. It works fine if the table doesn't exist. 

Possible a bug here
https://github.com/vertica/dbt-vertica/blob/master/dbt/include/vertica/macros/materializations/models/incremental/incremental.sql#L49

**Comment by ajay-abrol2** [comment]
Code has been merged in dbt vertica 1.4.0.
