### ISSUE TITLE
BUG: don't handle status in multi queries models

### ISSUE THREAD

**Issue by barloc** [vertica/dbt-vertica#75]
Hello.
I did fix for old version dbt: [fix](https://github.com/barloc/dbt-vertica/blob/ddacbd3e9ca5890745d636939b92b41f2af9c963/dbt/adapters/vertica/connections.py#L104) and other in this file
If dbt sends multiquery to the vertica with ';' separator then dbt adapter doesn't check result for second...any query except first query.
So dbt reports thats it's ok, but the table is broken (not updated...). 
For more see doc for the [vertica_python](https://github.com/vertica/vertica-python#frequently-asked-questions-speech_balloon) -> Why does my query not throw an error?

**Comment by barloc** [comment]
I think it is critical bug. When I fix it I found bug with partitions in incremental tables.

**Comment by ajay-abrol2** [comment]
Code has been merged in dbt vertica 1.4.0.
