### ISSUE TITLE
BUG: partitions for incremental tables

### ISSUE THREAD

**Issue by barloc** [vertica/dbt-vertica#78]
Without fix from https://github.com/vertica/dbt-vertica/issues/74 adapter skips that error.
But with fix there is error - when incremental table with partitions updated then adds alter for temp table and it's not correct.
Error: `Partitioning not supported for temporary tables`

See https://github.com/vertica/dbt-vertica/blob/3b718e472c77d39c4644de0ec88ee1a022c59180/dbt/include/vertica/macros/materializations/models/incremental/incremental.sql#L54 where create temp table and adds alter https://github.com/vertica/dbt-vertica/blob/3b718e472c77d39c4644de0ec88ee1a022c59180/dbt/include/vertica/macros/materializations/models/table/create_table_as.sql#L36

**Comment by ajay-abrol2** [comment]
Code has been merges in dbt vertica 1.4.0
